[package]
name = "path_svg"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.2"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
build = "scarb build"
check = "scarb check"